"""Link-budget models and calculations for the PTIG presentation."""

from .calculations import (
    build_link_budget_state,
    compute_cnr,
    compute_cnr_ref,
    compute_eirp,
    compute_free_space_path_loss,
    compute_modulation_order,
    compute_r_eff,
    compute_slant_range,
    compute_two_way_latency_s,
)
from .models import (
    Band,
    BitErrorRateThreshold,
    DataChannel,
    FreqBandType,
    Link,
    LinkDirection,
    ModulationScheme,
    OrbitType,
    PropagationLosses,
    Satellite,
    UserEquipment,
    WaveformParameters,
)

__all__ = [
    "Band",
    "BitErrorRateThreshold",
    "DataChannel",
    "FreqBandType",
    "Link",
    "LinkDirection",
    "ModulationScheme",
    "OrbitType",
    "PropagationLosses",
    "Satellite",
    "UserEquipment",
    "WaveformParameters",
    "build_link_budget_state",
    "compute_cnr",
    "compute_cnr_ref",
    "compute_eirp",
    "compute_free_space_path_loss",
    "compute_modulation_order",
    "compute_r_eff",
    "compute_slant_range",
    "compute_two_way_latency_s",
]
